// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/agentbox.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceCode    string                 `protobuf:"bytes,1,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
	Runtime       string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_agentbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentbox_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *ExecuteRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_agentbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentbox_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_proto_agentbox_proto protoreflect.FileDescriptor

const file_proto_agentbox_proto_rawDesc = "" +
	"\n" +
	"\x14proto/agentbox.proto\"J\n" +
	"\x0eExecuteRequest\x12\x1e\n" +
	"\n" +
	"sourceCode\x18\x01 \x01(\tR\n" +
	"sourceCode\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\"E\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1a\n" +
	"\bexitCode\x18\x02 \x01(\x05R\bexitCode2@\n" +
	"\x10ExecutionService\x12,\n" +
	"\aExecute\x12\x0f.ExecuteRequest\x1a\x10.ExecuteResponseB/Z-github.com/AnandRaj2224/agentbox/internal/apib\x06proto3"

var (
	file_proto_agentbox_proto_rawDescOnce sync.Once
	file_proto_agentbox_proto_rawDescData []byte
)

func file_proto_agentbox_proto_rawDescGZIP() []byte {
	file_proto_agentbox_proto_rawDescOnce.Do(func() {
		file_proto_agentbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentbox_proto_rawDesc), len(file_proto_agentbox_proto_rawDesc)))
	})
	return file_proto_agentbox_proto_rawDescData
}

var file_proto_agentbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_agentbox_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: ExecuteRequest
	(*ExecuteResponse)(nil), // 1: ExecuteResponse
}
var file_proto_agentbox_proto_depIdxs = []int32{
	0, // 0: ExecutionService.Execute:input_type -> ExecuteRequest
	1, // 1: ExecutionService.Execute:output_type -> ExecuteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_agentbox_proto_init() }
func file_proto_agentbox_proto_init() {
	if File_proto_agentbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentbox_proto_rawDesc), len(file_proto_agentbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentbox_proto_goTypes,
		DependencyIndexes: file_proto_agentbox_proto_depIdxs,
		MessageInfos:      file_proto_agentbox_proto_msgTypes,
	}.Build()
	File_proto_agentbox_proto = out.File
	file_proto_agentbox_proto_goTypes = nil
	file_proto_agentbox_proto_depIdxs = nil
}
